public class AreaCalculator(){
    // คำนวนพื้นที่ของ Circle
    public int calcAreaCircle(Circle circle) ...
    // คำณวนพื้นที่ของ Ractangle
    public int calAreaRactangle(Ractangle ractangle) ...
}